### ISSUE TITLE
Monolog compatibility issue 

### ISSUE THREAD

**Issue by Shotman** [getparthenon/monorepo#37]
### Parthenon version(s) affected

2.1.1

### Description

Error while installing parthenon, when using any bin/console command

"Fatal error: Declaration of Parthenon\Common\Logging\Monolog\ProcessIdProcessor::__invoke(array $record): array must be compatible with Monolog\Processor\ProcessorInterface::__invoke(Monolog\LogRecord $record): Monolog\LogRecord in [PATH]\vendor\parthenon\parthenon\src\Common\Logging\Monolog\ProcessIdProcessor.php on line 27"

Same issue would happen with ExceptionProcessor, RequestProcessor and SessionProcessor

They all use array as a type for their __invoke method when LogRecord object is required by the interface

### How to reproduce

I just installed parthenon with the composer create-project command

### Additional Context

Tested on PHP 8.2 and 8.1

**Comment by that-guy-iain** [comment]
Sorry, I just noticed this. This was fixed in 2.1.2
